mail:
  invite:
    subject: "招待登録のお知らせ"
    body: |
      こんにちは {{username}} さん、

      あなたは {{system}} への招待を受けています。
      あなたの一時ログインID：{{loginId}}
      あなたの一時ログインパスワード：{{otpPwd}}
      
      下記リンクから登録を進めてください：

      {{link}}

      このリンクの有効期限は1時間です。必ず時間内に実施してください。